import type { Config, Context } from "@netlify/edge-functions";

const css = String.raw`
#resources .library-knowledge-section{display:none!important}
#resources .lib-item{display:flex;flex-direction:column;gap:10px;text-align:right}
#resources .lib-item h3{margin:0!important;padding-bottom:9px;border-bottom:1px solid #e3eaed;color:#274f64!important;line-height:1.5;unicode-bidi:plaintext;text-align:start;overflow-wrap:anywhere}
#resources .lib-biblio{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px!important}
#resources .lib-biblio span{display:flex!important;flex-direction:column;gap:2px;padding:7px 8px;border:1px solid #e3eaed;border-radius:5px;background:#f8fafb;min-width:0;font-size:11.5px!important;line-height:1.45;unicode-bidi:plaintext;overflow-wrap:anywhere}
#resources .lib-biblio strong{display:block;color:#6e818b;font-size:10px;font-weight:650}
#resources .lib-item p{margin:0!important;padding:9px 10px;border-right:3px solid #91b4c0;background:#f5f9fa;color:#49616d!important;line-height:1.65!important;unicode-bidi:plaintext;overflow-wrap:anywhere}
#resources .lib-item a{display:inline-flex;align-items:center;align-self:flex-start;min-height:28px;padding:0 10px;border:1px solid #bcd0d7;border-radius:4px;color:#23668b!important;text-decoration:none}
.gallery-mode-switch{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0 16px}.gallery-mode-switch button{appearance:none;border:1px solid #cbd8de;background:#fff;color:#496573;border-radius:5px;padding:8px 12px;font:inherit;font-size:12.5px;cursor:pointer}.gallery-mode-switch button.active{background:#355f78;color:#fff;border-color:#355f78}.gallery-single-note{font-size:11.5px;color:#71808a;line-height:1.5}.gallery-media-item.single-media{align-items:center}.gallery-media-item.single-media .gallery-media-fields{padding-left:16px}
@media(max-width:600px){#resources .lib-biblio{grid-template-columns:1fr}}
`;

const script = String.raw`
(()=>{
  let mode="single";
  const root=()=>document.getElementById("adminGallery");
  const byId=id=>document.getElementById(id);
  const escapeHtml=value=>String(value??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]));
  const escapeAttr=escapeHtml;
  const setStatus=(text,type="")=>{const e=byId("gallerySaveStatus");if(e){e.textContent=text||"";e.className="inline-status "+type}};
  const cleanKnowledge=()=>document.querySelector(".library-knowledge-section")?.remove();
  function replaceCountryField(){const old=byId("libraryCountry");if(!old||old.tagName!=="SELECT")return;const input=document.createElement("input");input.id="libraryCountry";input.setAttribute("list","libraryCountrySuggestions");input.placeholder="מדינה או אזור";input.setAttribute("aria-label","חיפוש לפי מדינה או אזור");input.oninput=()=>window.renderLibraryExplorer?.();const list=document.createElement("datalist");list.id="libraryCountrySuggestions";["ישראל","בין־לאומי","אירופה","ארצות הברית","אוקראינה","לבנון"].forEach(value=>{const option=document.createElement("option");option.value=value;list.append(option)});old.replaceWith(input);input.after(list)}
  function sourceLayout(){document.querySelectorAll("#resources .lib-item").forEach(card=>card.classList.add("source-card"))}
  function mediaCard(m,index,pending){const src=pending?m.preview:(m.url||"/api/file?key="+encodeURIComponent(m.key));const kind=pending?"תמונה חדשה":"תמונה קיימת";const remove="window.__galleryRemove("+(pending?"true":"false")+","+index+")";if(mode==="single")return '<div class="gallery-media-item single-media"><button type="button" class="gallery-remove-x" onclick="'+remove+'" title="הסרת תמונה">×</button><img class="gallery-media-thumb" src="'+escapeAttr(src)+'" alt=""><div class="gallery-media-fields"><div class="gallery-media-kind">'+kind+(m.name?" · "+escapeHtml(m.name):"")+'</div><div class="gallery-single-note">הכותרת, הקרדיט והתאריך נלקחים מהפרטים שמעל.</div></div></div>';const edit="window.__galleryEdit("+(pending?"true":"false")+","+index+",";return '<div class="gallery-media-item"><button type="button" class="gallery-remove-x" onclick="'+remove+'" title="הסרת תמונה">×</button><img class="gallery-media-thumb" src="'+escapeAttr(src)+'" alt=""><div class="gallery-media-fields"><div class="gallery-media-kind">'+kind+(m.name?" · "+escapeHtml(m.name):"")+'</div><input value="'+escapeAttr(m.title||"")+'" oninput="'+edit+'\'title\',this.value)" placeholder="כותרת התמונה (רשות)"><input value="'+escapeAttr(m.credit||"")+'" oninput="'+edit+'\'credit\',this.value)" placeholder="צילום / קרדיט (רשות)"><input type="date" value="'+escapeAttr(m.date||"")+'" oninput="'+edit+'\'date\',this.value)" title="תאריך צילום (רשות)"></div></div>'}
  function renderMedia(){const existing=byId("galleryExistingMedia"),pending=byId("galleryPendingMedia");if(existing)existing.innerHTML=galleryEditMedia.map((m,i)=>mediaCard(m,i,false)).join("");if(pending)pending.innerHTML=galleryPendingFiles.map((m,i)=>mediaCard(m,i,true)).join("")}
  function applyMode(next){mode=next==="album"?"album":"single";const album=mode==="album",files=byId("galleryFiles"),single=byId("galleryModeSingle"),multiple=byId("galleryModeAlbum"),title=byId("galleryTitle"),date=byId("galleryDate"),credit=byId("galleryCredit"),description=byId("galleryDescription"),button=byId("galleryFilesButton"),hint=byId("galleryUploadHint"),heading=byId("galleryMediaHeading"),note=byId("galleryMediaNote"),adminNote=byId("galleryAdminNote");if(files)files.multiple=album;if(single)single.classList.toggle("active",!album);if(multiple)multiple.classList.toggle("active",album);if(title){title.closest("label").childNodes[0].textContent=album?"כותרת האלבום / האירוע*":"כותרת התמונה*"}if(date){date.closest("label").childNodes[0].textContent=album?"תאריך האירוע*":"תאריך הצילום*"}if(credit)credit.closest("label").hidden=album;if(description){description.closest("label").childNodes[0].textContent=album?"טקסט כללי על האירוע":"תיאור / הקשר";description.placeholder=album?"תיאור כללי של האירוע או ההקשר.":"תיאור התמונה או ההקשר שלה."}if(button)button.textContent=album?"＋ הוספת תמונות":"＋ בחירת תמונה";if(hint)hint.textContent=album?"אפשר לבחור כמה תמונות בבת אחת, ולהוסיף עוד תמונות לאחר מכן.":"לתמונה אחת ממלאים כאן את כל הפרטים.";if(heading)heading.textContent=album?"פרטי תמונה אופציונליים":"תמונה שנבחרה";if(note)note.textContent=album?"אפשר, אך לא חובה, להוסיף לכל תמונה כותרת, קרדיט או תאריך משלה.":"הפרטים של התמונה נלקחים מהשדות שמעל.";if(adminNote)adminNote.textContent=album?"באלבום ממלאים פעם אחת את פרטי האירוע. הפרטים של כל תמונה הם רשות, והתמונה הראשונה משמשת כתמונת שער.":"בתמונה אחת יש למלא כותרת, תאריך צילום וקרדיט. התיאור הוא רשות.";renderMedia()}
  function addFiles(files){for(const file of files){if(!file.type.startsWith("image/")){setStatus('הקובץ "'+file.name+'" אינו תמונה ולכן לא נוסף.','error');continue}if(mode==="single"&&(galleryEditMedia.length||galleryPendingFiles.length)){setStatus("במסלול תמונה אחת ניתן לבחור תמונה אחת בלבד. להוספת תמונה אחרת, הסירו תחילה את התמונה הנוכחית או עברו לאלבום.","error");break}galleryPendingFiles.push({file,preview:URL.createObjectURL(file),title:"",credit:"",date:""});if(mode==="single")break}renderMedia()}
  async function save(){const eventTitle=byId("galleryTitle").value.trim(),eventDate=byId("galleryDate").value,credit=byId("galleryCredit").value.trim(),existing=galleryEditMedia,pending=galleryPendingFiles,count=existing.length+pending.length,album=mode==="album";if(!eventTitle){setStatus(album?"יש להזין כותרת לאלבום / לאירוע.":"יש להזין כותרת לתמונה.","error");return}if(!eventDate){setStatus(album?"יש להזין תאריך אירוע.":"יש להזין תאריך צילום.","error");return}if(!count){setStatus("יש לבחור לפחות תמונה אחת.","error");return}if(!album&&count!==1){setStatus("במסלול תמונה אחת ניתן לפרסם תמונה אחת בלבד.","error");return}if(!album&&!credit){setStatus("יש להזין צילום / קרדיט לתמונה.","error");return}const publish=()=>root()?.querySelector(".gallery-publish-btn");const pub=publish();if(pub){pub.disabled=true;pub.textContent="מפרסם..."}try{const metadata=m=>album?{title:String(m.title||"").trim(),credit:String(m.credit||"").trim(),date:String(m.date||"").trim()}:{title:eventTitle,credit,date:eventDate};const media=existing.map(({key,name,type,...m})=>({key,name,type,...metadata(m)}));for(let i=0;i<pending.length;i++){setStatus("מעלה תמונה "+(i+1)+" מתוך "+pending.length+": "+pending[i].file.name);const uploaded=await uploadOneGalleryFile(pending[i].file);media.push({...uploaded,...metadata(pending[i])})}const body={id:byId("galleryId").value||undefined,title:eventTitle,date:eventDate,description:byId("galleryDescription").value.trim(),media,uploadMode:mode,active:byId("galleryActive").checked};const response=await fetch("/api/gallery",{method:body.id?"PUT":"POST",headers:apiHeaders(),body:JSON.stringify(body)});const json=await response.json().catch(()=>({}));if(!response.ok)throw new Error(json.message||"שמירת הגלריה נכשלה");setStatus("הפריט נשמר בהצלחה.","success");clear(false);if(currentAccessRole==="admin")await loadAdminGallery();await loadGallery()}catch(error){setStatus(error.message||"פרסום הגלריה נכשל.","error")}finally{if(pub){pub.disabled=false;pub.textContent="פרסום"}}}
  function clear(clearStatus=true){byId("galleryId").value="";byId("galleryTitle").value="";byId("galleryDate").value="";byId("galleryCredit").value="";byId("galleryDescription").value="";byId("galleryFiles").value="";byId("galleryActive").checked=true;galleryEditMedia=[];galleryPendingFiles.forEach(x=>x.preview&&URL.revokeObjectURL(x.preview));galleryPendingFiles=[];applyMode("single");if(clearStatus)setStatus("")}
  function edit(id){const item=adminGalleryCache.find(row=>row.id===id);if(!item)return;byId("galleryId").value=item.id;byId("galleryTitle").value=item.title||"";byId("galleryDate").value=item.date||"";byId("galleryDescription").value=item.description||"";byId("galleryActive").checked=item.active!==false;galleryEditMedia=(item.media||[]).map(media=>({...media,title:media.title||"",credit:media.credit||"",date:media.date||""}));galleryPendingFiles=[];byId("galleryCredit").value=item.media?.[0]?.credit||"";applyMode(item.uploadMode||(item.media?.length>1?"album":"single"));setStatus("");root()?.scrollIntoView({behavior:"smooth"})}
  function configureGallery(){const area=root();if(!area||area.dataset.presentationV66)return;area.dataset.presentationV66="1";const bar=area.querySelector(".gallery-publish-bar"),title=byId("galleryTitle"),date=byId("galleryDate");bar?.querySelector(".gallery-publish-btn")?.remove();[...area.querySelectorAll(".gallery-publish-btn")].slice(0,-1).forEach(button=>button.remove());if(!byId("galleryModeSingle")){const switcher=document.createElement("div");switcher.className="gallery-mode-switch";switcher.innerHTML='<button id="galleryModeSingle" type="button">תמונה אחת</button><button id="galleryModeAlbum" type="button">אלבום תמונות</button>';bar.after(switcher);byId("galleryModeSingle").onclick=()=>applyMode("single");byId("galleryModeAlbum").onclick=()=>applyMode("album")}if(date&&!byId("galleryCredit")){const label=document.createElement("label");label.innerHTML='צילום / קרדיט*<input id="galleryCredit" placeholder="שם הצלם/ת או בעל/ת הזכויות">';date.closest("label").after(label)}title?.closest("label").setAttribute("id","galleryTitleWrap");date?.closest("label").setAttribute("id","galleryDateWrap");const description=byId("galleryDescription");description?.closest("label").setAttribute("id","galleryDescriptionWrap");const addButton=area.querySelector(".gallery-add-images");if(addButton)addButton.id="galleryFilesButton";const hint=area.querySelector(".gallery-upload-zone span");if(hint)hint.id="galleryUploadHint";const heading=area.querySelector(".gallery-media-heading");if(heading)heading.id="galleryMediaHeading";if(!byId("galleryMediaNote")&&heading){const note=document.createElement("p");note.id="galleryMediaNote";note.className="gallery-single-note";heading.after(note)}const adminNote=area.querySelector(".admin-note");if(adminNote)adminNote.id="galleryAdminNote";const files=byId("galleryFiles");files?.addEventListener("change",event=>{event.stopImmediatePropagation();addFiles([...event.target.files]);event.target.value=""},true);area.addEventListener("click",event=>{const button=event.target.closest(".gallery-publish-btn");if(button){event.preventDefault();event.stopImmediatePropagation();save()}const editButton=event.target.closest("#adminGalleryList button");const match=editButton?.getAttribute("onclick")?.match(/editGalleryItem\('([^']+)'\)/);if(match){event.preventDefault();event.stopImmediatePropagation();edit(match[1])}} ,true);applyMode("single")}
  window.__galleryRemove=(pending,index)=>{const rows=pending?galleryPendingFiles:galleryEditMedia;const item=rows[index];if(item?.preview)URL.revokeObjectURL(item.preview);rows.splice(index,1);renderMedia()};
  window.__galleryEdit=(pending,index,field,value)=>{const item=(pending?galleryPendingFiles:galleryEditMedia)[index];if(item)item[field]=value};
  window.setGalleryMode=applyMode;window.__presentationSaveGallery=save;window.__presentationClearGallery=clear;window.editGalleryItem=edit;
  const observe=()=>{cleanKnowledge();replaceCountryField();sourceLayout();configureGallery()};
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",observe);else observe();new MutationObserver(observe).observe(document.documentElement,{childList:true,subtree:true});
})();
`;

export default async (_request: Request, context: Context) => {
  const response = await context.next();
  if (!response.headers.get("content-type")?.includes("text/html")) return response;
  const html = await response.text();
  if (html.includes("presentation-v66")) return response;
  const headers = new Headers(response.headers);
  headers.delete("content-length");
  const injected = `<style id="presentation-v66">${css}</style><script id="presentation-v66">${script}</script>`;
  return new Response(html.replace("</head>", `${injected}</head>`), { status: response.status, statusText: response.statusText, headers });
};

export const config: Config = { path: "/*", excludedPath: "/api/*", onError: "bypass" };
